services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    env_file: .env

  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    env_file: .env
